dependencies:
  - python=3
  - pip:
    - spacy
    - ipykernel
    - scipy
    - numpy
    - scikit-learn
    - matplotlib
    - pandas
    - thinc
    - torch
    - torchvision
    - xlrd
    - openpyxl
    - tensorflow
